name: 'Firestore Data'
description: 'Read or write data from Firestore'
inputs:
  firebaseServiceAccount:  # id of input
    description: 'Firebase service account JSON'
    required: true
  path:
    description: 'Path to read or write'
    required: true
  key:
    description: 'Key on document to read or write'
    required: true
  value:
    description: 'Value to read or write (optional)'
outputs:
  value: # id of output
    description: 'Value at path after action'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  color: 'orange'
  icon: 'database'
